### ISSUE TITLE
What happened to the website

### ISSUE THREAD

**Issue by ffflick-gh** [splintah/configuration#2]
Sorry, I don't know how else to reach you. You had a website with a blog post series on polymorpic lambda calculus. I can't find it, is it possible to access it somehow? Thank you!

**Comment by splintersuidman** [comment]
You can still find the articles [on the Internet Archive](https://web.archive.org/web/20211130145553/https://splintah.github.io/). Hope this helps! I took them down with my site once because I planned on making a new one, but I’ve never actually done that…

**Comment by splintersuidman** [comment]
I’ve also made an archived version of the old site public [here](https://github.com/splintah/old-site).

**Comment by ffflick-gh** [comment]
Thanks so much!
